config/routes.rb
Rails.application.routes.draw do

  resources :letters

  root :to => 'welcomes#index'

  resources :user_sessions
  resources :abouts

  resources :blog_articles do
    resources :comments, only:[:new, :create, :destroy]
  end


  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users 

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :blog_articles
  has_many :comments, through: :blog_articles 

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  validate :must_have_certain_details


  def blogs_in_order
    blog_articles.order(created_at: :desc)
  end

  


  private
  def must_have_certain_details
    if email != APP_CONFIG['EMAIL'] || password != APP_CONFIG['PASSWORD']
      errors.add(:email, 'not authorized')
    end
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:new, :create, :edit, :index]


  def show
    @user = User.find(params[:id])
  end

 
  def new
    @user = User.new
  end



  def create
    @user = User.new(user_params)

      if @user.save
        auto_login(@user)
        redirect_to user_path(@user), notice: 'Profile successfully created' 
        
      else
        render :new 
      end  
  end

  def index
    redirect_to root_path
  end

  def edit
    redirect_to root_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_blog_article_form.html.erb
<h3>New Blog Article</h3>  

<%= form_for ([@user, @blog_article]), :remote => true do |f| %>
  
  <%= render :partial => 'blog_articles_form_errors' %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :publish_now %><br>
    <%= f.select :publish_now, [['yes','yes'], ['no','no']] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_blog_articles_form_errors.html.erb
<% if @blog_article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@blog_article.errors.count, "error") %> prohibited this blog_article from being saved:</h2>

    <ul>
    <% @blog_article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class='row'>
      <div class='col-lg-4'></div>
      <div class='col-lg-4' align='center'>
        <div class="error_div">
          <h3 class='error_header'><%= pluralize(@user.errors.count, "error")%></h3>
          <p>stopped this account from saving</p>
        </div>
      </div>
      <div class='col-lg-4'></div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.button %>
  </div>
<% end %>

app/views/users/_published_blog_list.html.erb
<h4>Published Blog Posts</h4>
<% @user.blogs_in_order.each do |blog| %>
  <% if blog.publish_now == 'yes' %>
    <div>
      <% if blog == @user.blogs_in_order.first %>
        <h6>Most Recent</h6>
      <% end %>

      <h5><%= blog.title %></h5>
      <p><%= blog.body %></p>
      <p>Published: <%= blog.publish_now %></p>
      <p>Created at: <%= blog.created_at %></p>
      <button type="button"><%= link_to 'Edit', edit_blog_article_path(blog) %></button>
      <button type="button"><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
  <% end %>
<% end %>

app/views/users/_unpublished_blog_list.html.erb
<h4>Unpublished Blog Posts</h4>
<% @user.blogs_in_order.each do |blog| %>
  <% if blog.publish_now == 'no' %>
    <div>
      <% if blog == @user.blogs_in_order.first %>
        <h6>Most Recent</h6>
      <% end %>

      <h5><%= blog.title %></h5>
      <p><%= blog.body %></p>
      <p>Published: <%= blog.publish_now %></p>
      <p>Created at: <%= blog.created_at %></p>
      <button type="button"><%= link_to 'Edit', edit_blog_article_path(blog) %></button>
      <button type="button"><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-lg-3'></div>
  <div class='col-lg-6' align='center'>
    <div id='form_border'>
      <h1>User Account</h1>
      <%= render 'form' %>
    </div>  
  </div>
  <div class='col-lg-3'></div>
</div>


<div class="btn-group btn-group-justified" id='users_footer'>
  <div class="btn-group">
    <%= link_to(abouts_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>About Me</span></button>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to(blog_articles_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>Blog</span></button>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to(new_letter_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>Contact</span></button>
    <% end %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $('button')
      .eq(1)
      .addClass('btn btn-info');

});
</script>

app/views/users/show.html.erb
<h1>Hello <%= @user.email %></h1>

<button><%= link_to 'New Blog Article', new_blog_article_path %></button>
<button><%= link_to 'Sent Letters', letters_path %></button>

<div id='published'>

  <%= render 'published_blog_list' %>

</div>

<div id='unpublished'>

  <%= render 'unpublished_blog_list' %>

</div>