config/routes.rb
Rails.application.routes.draw do

  resources :letters

  root :to => 'welcomes#index'

  resources :user_sessions
  resources :abouts

  resources :blog_articles do
    resources :comments, only:[:new, :create, :destroy]
  end


  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users 

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/blog_article.rb
class BlogArticle < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :publish_now, presence: true

  validate :publish_now_is_yes_or_no


  private
  def publish_now_is_yes_or_no
    unless publish_now == nil

      if publish_now.downcase != 'yes' && publish_now.downcase != 'no'
        errors.add(:publish_now, 'must be yes or no')
      end

    end    
  end
end

app/controllers/blog_articles_controller.rb
class BlogArticlesController < ApplicationController

  skip_before_filter :require_login, only: [:index, :show]
      


  def index
    @blog_articles = BlogArticle.order(created_at: :desc).where(publish_now: 'yes')
  end

  # GET /blog_articles/1
  # GET /blog_articles/1.json
  def show
    @blog_article = BlogArticle.find(params[:id])
  end

  # GET /blog_articles/new
  def new
    @blog_article = BlogArticle.new
  end

  # GET /blog_articles/1/edit
  def edit
    @blog_article = BlogArticle.find(params[:id])
  end
  

  # POST /blog_articles
  # POST /blog_articles.json
  def create
    @blog_article = BlogArticle.new(blog_article_params)
    @blog_article.user = current_user

    respond_to do |format|
      if @blog_article.save
        format.html { redirect_to user_path(current_user), notice: 'Blog article was successfully created.' }
        format.js {}
      else
        format.html { render :new, alert: 'there was an error' }
        format.js {}
      end
    end
  end

  # PATCH/PUT /blog_articles/1
  # PATCH/PUT /blog_articles/1.json
  def update
    @blog_article = BlogArticle.find(params[:id])
    respond_to do |format|
      if @blog_article.update(blog_article_params)
        format.html { redirect_to user_path(current_user), notice: 'Blog article was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_article }
      else
        format.html { render :edit }
        format.json { render json: @blog_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_articles/1
  # DELETE /blog_articles/1.json
  def destroy
    @blog_article = BlogArticle.find(params[:id])
    @blog_article.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Blog article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_user
      @blog_article = BlogArticle.find(params[:id])
    end

    def blog_article_params
      params.require(:blog_article).permit(:body, :title, :publish_now)
    end

end

app/helpers/blog_articles_helper.rb
module BlogArticlesHelper
end

app/views/blog_articles/_blog_article.html.erb
<% if blog_article.publish_now.downcase == 'yes' %>
  <h2><%= link_to blog_article.title, blog_article_path(blog_article.id) %></h2>
  <div >
    <p class='created_on'>Created on: <%= blog_article.created_at %></p>
    <div class='blog_body'><%= blog_article.body %></div>
    <br>
  </div>
<% end %>

app/views/blog_articles/_form.html.erb
<%= form_for(@blog_article) do |f| %>
  <% if @blog_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_article.errors.count, "error") %> prohibited this blog_article from being saved:</h2>

      <ul>
      <% @blog_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <p><b>Remember Enter Creates New Paragraph!</b></p>
  <div class="field">
    <%= f.cktext_area :body %>
  </div>
  <div class="field">
    <%= f.label :publish_now %><br>
    <%= f.select :publish_now, [['yes','yes'], ['no','no']] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_articles/edit.html.erb
<h1>Editing blog_article</h1>

<%= "Editing #{@blog_article.title}" %>
<%= render 'form' %>

<%= link_to 'Show', @blog_article %> |
<%= link_to 'Back', blog_articles_path %>

app/views/blog_articles/index.html.erb
<div class='row'>
  <div class='col-lg-4'></div>
  <div class='col-lg-4' align='center'>
    <h1>The Blog</h1>
  </div>
  <div class='col-lg-4'></div>
</div>

<div class='row'>
  <div class='col-lg-2'></div>
  <div class='col-lg-5'>
    <%= render @blog_articles %>
  </div>
  <div class='col-lg-2'></div>
  <div class='col-lg-2'>
    <h4>Most Recent Posts</h4>
    <div class='btn-group-vertical'>
      <% @blog_articles.limit(10).each do |blog| %>
        <% if blog.publish_now.downcase == 'yes' %>
          <button type='button' class='btn btn-default'>
            <%= link_to blog.title, blog_article_path(blog) %>
          </button>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class='col-lg-1'></div>

</div>

  



<div class="btn-group btn-group-justified" id='blog_articles_footer'>
  <div class="btn-group">
    <%= link_to(abouts_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>About Me</span></button>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to(root_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>Welcome</span></button>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to(new_letter_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>Contact</span></button>
    <% end %>
</div>

<script type="text/javascript">
  

    
    var temp = 1;

    replace();

    function replace(){
      $.each($('.blog_body'), function() { 
        temp = $(this).text();
        $(this).text('');
        $(this).html(temp);
      });
    }
  

  
</script>

app/views/blog_articles/new.html.erb
<h1>New blog Article</h1>

<div class='row'>
  <div class='col-lg-5'>
    <%= render 'form' %>
  </div>
  <div class='col-lg-6'></div>
</div>


<%= link_to 'Back', blog_articles_path %>

app/views/blog_articles/show.html.erb
<h3><%= @blog_article.title %></h3>
<p>Created at: <%= @blog_article.created_at %></p>
<div class='blog_body'><%= @blog_article.body %></div>

<script type="text/javascript">

    

    var temp = 1;

    replace();

    function replace(){
      $.each($('.blog_body'), function() { 
        temp = $(this).text();
        $(this).text('');
        $(this).html(temp);
      });
    }
</script>