config/routes.rb
Rails.application.routes.draw do

  resources :letters

  root :to => 'welcomes#index'

  resources :user_sessions
  resources :abouts

  resources :blog_articles do
    resources :comments, only:[:new, :create, :destroy]
  end


  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users 

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login
  
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_to user_path(@user), notice: 'Login Successful'
    else
      flash.now[:alert] = 'Login Failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged Out!'
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= button_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class='row'>
  <div class='col-lg-3'></div>
  <div class='col-lg-6' align='center'>
    <div id='form_border'>
      <h1>Admin Login</h1>
      <%= render 'form' %>
      <button class='btn btn-info' type='button'>
         <%= link_to 'Create Account', new_user_path, :id => 'white_text' %>
      </button>  
    </div>  
  </div>
  <div class='col-lg-3'></div>
</div>


<div class="btn-group btn-group-justified" id='user_sessions_footer'>
  <div class="btn-group">
    <%= link_to(abouts_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>About Me</span></button>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to(blog_articles_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>Blog</span></button>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to(new_letter_path) do %>
    <button type="button" class="btn btn-default"><span class='footer_text_color'>Contact</span></button>
    <% end %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $('button')
      .eq(1)
      .addClass('btn btn-info');

});
</script>