config/routes.rb
Rails.application.routes.draw do

  resources :letters

  root :to => 'welcomes#index'

  resources :user_sessions
  resources :abouts

  resources :blog_articles do
    resources :comments, only:[:new, :create, :destroy]
  end


  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users 

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div><a class="navbar-brand" id='exploding_name'><em>Drew Martin</em></a></div>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class='white_header_text'><%= link_to 'Welcome', root_path %></li>
        <li class='white_header_text'><%= link_to 'About Me', abouts_path%></li>
        <li class='white_header_text'><%= link_to 'Blog', blog_articles_path %></li>
        <li class='white_header_text'><%= link_to 'Contact',  new_letter_path %></li>
        <% if current_user.nil? %>
          <li class='white_header_text'><%= link_to 'Admin', login_path %></li>
        <% end %>  
        <% if current_user %>
          <li class='white_header_text'><%= link_to "Account Page", user_path(current_user.id) %></li>
          <li class='white_header_text'><%= link_to "Logout", :logout, method: :post %></li>
        <% end %> 

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Get Social<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class='white_header_text'><a href="https://github.com/drewemartin" target="_blank">Github</a></li>
            <li class='white_header_text'><a href="https://www.linkedin.com/pub/drew-martin/31/1b2/b84/" target="_blank">LinkedIn</a></li>
            <li class='white_header_text'><a href="https://twitter.com/DrewEMartin" target="_blank">Twitter</a></li>
            <li class='white_header_text'><a href="http://about.me/Drew_Martin" target='_blank'>About.me</a></li>
          </ul>
        </li>
      </ul>

    </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= render 'layouts/navbar' %>

<div class="container">

  <div class='row'>

      <% if flash[:notice] != nil %>
        <div class='col-lg-12' id='notice_div' align='center'>
          <h3 id="notice"><%= flash[:notice] %></h3>
        </div>        
      <% elsif flash[:alert] != nil %>
        <div class='col-lg-12' id='alert_div' align='center'>
          <h3 id="alert"><%= flash[:alert] %></h3>
        </div>
      <% end %>

  </div>

  <%= yield %>




 

</div>






</body>
</html>